### ISSUE TITLE
Error running track.py

### ISSUE THREAD

**Issue by umesh-timalsina** [kbvatral/MF-SORT#2]
I ran into an error when running the track.py code. I was wondering what the issue might be?

```python
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 794/794 [00:01<00:00, 543.42frames/s]
Traceback (most recent call last):
  File "/home/umesh/isis/oele-isis/MF-SORT/examples/track.py", line 27, in <module>
    trks = np.array(track_output)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (4902, 10) + inhomogeneous part.

````

**Comment by kbvatral** [comment]
Interesting. I have never seen this issue before. My guess is that it is related to the deprecation of array creation from ragged-nested sequences in numpy. We need to figure out why the `track_output` array is inhomogeneous. This array should a list of lists where each list contains a single formatted detection (length 10).

**Comment by kbvatral** [comment]
Issue was with the deprecated numpy behavior as expected. Latest commit should fix the issue by squeezing the output to a list of ints rather than a ragged list of numpy values. Please test and re-open if needed.
